### ISSUE TITLE
Testing Dualshock4 controller

### ISSUE THREAD

**Issue by EdgarSun** [rdepena/node-dualshock-controller#70]
thank you for making this awesome package, I met a problem when directly testing the example:

Error: device with VID:1356 PID:1476 not found
    at new Controller (/home/pi/akita/node_modules/dualshock-controller/src/controller.js:143:29)
    at dualShock (/home/pi/akita/node_modules/dualshock-controller/src/dualshock.js:19:12)
    at Object.<anonymous> (/home/pi/akita/node-dualshock-controller/examples/test4.js:4:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)

My controller is connected to raspbian via Bluetooth

**Comment by EdgarSun** [comment]
after testing via USB connection, it's still not work. I can get the device with node-hid.
 
<img width="274" alt="screen shot 2017-06-20 at 2 55 21 pm" src="https://user-images.githubusercontent.com/167755/27320382-9b036a86-55c8-11e7-8d9c-5fda7fedc911.png">

**Comment by EdgarSun** [comment]
Never mind, after switching to "dualShock4-alternate-driver.json" config, problem's been resolved!
